name: flutter_firebase_fire
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.7.4
  permission_handler: ^10.2.0
  firebase_storage: ^11.5.0
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.13.0
  dropdown_button2: ^2.3.9
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  google_nav_bar: ^5.0.6
  path_provider: ^2.1.1
  image_picker: ^1.0.5
  url_launcher: ^6.2.5
  geolocator: ^10.1.0
  flutter_svg: ^2.0.9
  geocoding: ^2.1.1
  animator: ^3.3.0
  shimmer: ^3.0.0
  timeago: ^3.6.0
  image: ^4.1.3
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Lobster
    - family: SingleDay
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
        - asset: assets/fonts/SingleDay-Regular.ttf
