// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN8OOPsZd8JAKHyVlyj5NL0GJHT9_PYxE',
    appId: '1:631999217749:web:d19af69018760eff0d14dc',
    messagingSenderId: '631999217749',
    projectId: 'fir-fire-bbbbc',
    authDomain: 'fir-fire-bbbbc.firebaseapp.com',
    storageBucket: 'fir-fire-bbbbc.appspot.com',
    measurementId: 'G-GZFG60XGBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAavieXUJKzXrV8K5EnaTjL8ruEK0yLM5Q',
    appId: '1:631999217749:android:67af5db081b39c0a0d14dc',
    messagingSenderId: '631999217749',
    projectId: 'fir-fire-bbbbc',
    storageBucket: 'fir-fire-bbbbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfaubwvitLon9uHuPhkvRyb8PjlSoE6WE',
    appId: '1:631999217749:ios:1ee0029056db151c0d14dc',
    messagingSenderId: '631999217749',
    projectId: 'fir-fire-bbbbc',
    storageBucket: 'fir-fire-bbbbc.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfaubwvitLon9uHuPhkvRyb8PjlSoE6WE',
    appId: '1:631999217749:ios:ab9d959a42d8b42b0d14dc',
    messagingSenderId: '631999217749',
    projectId: 'fir-fire-bbbbc',
    storageBucket: 'fir-fire-bbbbc.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseFire.RunnerTests',
  );
}
